---
  - name: Deploy tomcat package
    hosts: tomcat_server
    become: yes
    tasks:
      - name: Install package
        package:
          name: openjdk-11-jdk
          state: present
      - name: Create tomcat user group
        ansible.builtin.group:
          name: tomcat
          state: present
      - name: create tomcat user 
        ansible.builtin.user:
          name: tomcat
          password: devops
          state: present
          group: tomcat
      - name: donwload splunk debian file 
        get_url:
          url: https://apachemirror.wuchna.com/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
          dest: /tmp/apache-tomcat-9.0.46.tar.gz
      - name: create directory
        ansible.builtin.file:
          path: /opt/tomcat
          state: directory
      - name: Extract  /opt/tomcat
        ansible.builtin.unarchive:
          src: /tmp/apache-tomcat-9.0.46.tar.gz
          dest: /opt/tomcat
          remote_src: yes
      - name: Change file ownership, group and permissions
        ansible.builtin.file:
          path: /opt/tomcat/
          group: tomcat
          recurse: yes
          state: directory
      - name: Change file ownership, group and permissions
        ansible.builtin.file:
          path: /opt/tomcat/apache-tomcat-9.0.46/conf
          group: tomcat
          mode: 750
      - name: Chnage ownserhsip of webapps
        ansible.builtin.file:
          path: /opt/tomcat/apache-tomcat-9.0.46/webapps
          owner: tomcat
      - name: Chnage ownserhsip of work
        ansible.builtin.file:
          path: /opt/tomcat/apache-tomcat-9.0.46/work
          owner: tomcat
      - name: Chnage ownserhsip of temp
        ansible.builtin.file:
          path: /opt/tomcat/apache-tomcat-9.0.46/temp
          owner: tomcat
      - name: Chnage ownserhsip of logs
        ansible.builtin.file:
          path: /opt/tomcat/apache-tomcat-9.0.46/logs
          owner: tomcat
      - name: Creating linux service by copying tomcat service file
        ansible.builtin.copy:
          src: tomcat.service
          dest: /etc/systemd/system/tomcat.service
      - name: Just force systemd to reread configs (2.4 and above)
        ansible.builtin.systemd:
          daemon_reload: yes
      - name: Enable and start sprinpetclinic service
        systemd:
          name: tomcat.service
          enabled: yes 
          state: started

      

      

      




      
    