---
  - name: Deploy Lamp service
    hosts: lamp_server
    become: yes
    tasks:
      - name: Install apache package
        package: 
          name: "{{ apache_package }}"
          state: present
        notify: Package is installed
      - name: Install PHP package
        package:
          name: "{{ item }}"
          state: present
        loop: "{{ php_package_list }}"
      - name: Copying info.php file
        ansible.builtin.copy:
          src: info.php
          dest: "{{ php_log_file }}"
        notify:
          - file copied successfully 
          - restart apache service
    handlers: 
      - name: Package is installed
        debug:
          msg: "{{ apache_package }} is successfully installed"
      - name: file copied successfully
        debug:
          msg: "File copied successfully to {{ php_log_file }} " 
      - name: restart apache service
        service: 
          name: "{{ apache_package }} " 
          state: restarted

      
      



