---
  - name: Create service for spring pet clinic
    hosts: appserver
    become: yes
    tasks:
      - name: Update ubuntu packages and install java
        apt:
          name: openjdk-11-jdk
          update_cache: yes
          state: present
      - name: create directory
        ansible.builtin.file:
          path: /usr/share/springpetclinic/
          state: directory
      - name: download springpet clinic jar file 
        get_url: 
          url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
          dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
      - name: create user springbootuser
        ansible.builtin.user:
          name: springbootuser
          password: devops
          state: present
      - name: Chnage ownersip of the file springpet to  springbootuser
        ansible.builtin.file:
          path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
          owner: springbootuser
          group: springbootuser
          mode: 500
          state: file
      - name: Creating linux service by copying springpetclinic service file
        ansible.builtin.copy:
          src: springpetclinic.service
          dest: /etc/systemd/system/springpetclinic.service
      - name: Enable and start sprinpetclinic service
        systemd:
          name: springpetclinic.service
          enabled: yes 
          state: started


        