---
  - name: Test deployment of tomcat
    hosts: tomcat
    become: yes
    tasks:
      - name: Chang group permission of /opt/tomcat to tomcat
        ansible.builtin.file:
          path: /opt/tomcat/
          group: tomcat
          recurse: yes
          state: directory